// Copyright 2026 Zurich Instruments AG
// SPDX-License-Identifier: Apache-2.0

use crate::ExperimentNode;
use crate::operation::Operation;
use crate::types::MatchTarget;
use laboneq_common::named_id::NamedIdStore;

use laboneq_common::uid::{HandleUid, PulseUid, VariableUid};
use laboneq_units::angle::Angle64;
use laboneq_units::duration::{Frequency, Hertz};

#[derive(Debug, Clone, PartialEq, Default)]
pub struct HqcsDeclarations {
    pub coprocessors: Vec<CoprocessorDecl>,
    pub mappings: Vec<CoprocessorMappingDecl>,
    pub streams: Vec<StreamDecl>,
    pub variables: Vec<VariableDecl>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CoprocessorDecl {
    pub label: String,
    pub payload: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CoprocessorMappingDecl {
    pub label: String,
    pub inventory_key: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StreamEndpoint {
    ControlSystem,
    /// Index into `HqcsDeclarations::coprocessors`.
    Coprocessor(u32),
}

#[derive(Debug, Clone, PartialEq)]
pub struct StreamDecl {
    /// Unique per experiment; autogenerated `stream_N` when the user did not
    /// provide one.
    pub uid: String,
    pub src: StreamEndpoint,
    pub dst: StreamEndpoint,
    pub link: Option<String>,
    pub fields: Vec<StreamFieldDecl>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct StreamFieldDecl {
    pub name: String,
    pub ty: VarType,
    pub binding: FieldBinding,
}

#[derive(Debug, Clone, PartialEq)]
pub enum FieldBinding {
    /// Outbound literal-at-send-time field, or inbound field nobody consumes.
    Unbound,
    /// Outbound acquisition field: handles feeding this field.
    Handles(Vec<HandleUid>),
    /// Inbound scalar field: variable it updates.
    Variable(VariableUid),
    /// Inbound waveform field: pulse it updates.
    Pulse(PulseUid),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VarType {
    Int8,
    Int16,
    Int32,
    Int64,
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Phase,
    Frequency,
    Amplitude,
    DiscriminationDataPacked,
    IqDataPacked,
    ScopeShot,
    WaveformUpdate,
}

#[derive(Debug, Clone, PartialEq)]
pub struct VariableDecl {
    pub ty: VarType,
    /// User-facing name for error messages; `None` when unset.
    pub name: Option<String>,
    pub initial: Option<VariableValue>,
    /// Results-capture handle; `None` = not logged.
    pub log_handle: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum VariableValue {
    Int(i64),
    Float(f64),
    Phase(Angle64),
    Frequency(Frequency<Hertz>),
    Amplitude(f64),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CmpOp {
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Predicate {
    Comparison {
        variable: VariableUid,
        op: CmpOp,
        rhs: VariableValue,
    },
    IsLive(IsLiveTarget),
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum IsLiveTarget {
    Variable(VariableUid),
    Pulse(PulseUid),
}

pub fn find_hqcs_declaration(hqcs: &HqcsDeclarations) -> Option<&'static str> {
    if !hqcs.coprocessors.is_empty() {
        return Some("coprocessor handles");
    }
    if !hqcs.streams.is_empty() {
        return Some("streams");
    }
    if !hqcs.mappings.is_empty() {
        return Some("coprocessor mappings");
    }
    if !hqcs.variables.is_empty() {
        return Some("variables");
    }
    None
}

/// Describe the first HQCS construct in the tree for error messages
/// (e.g. `do_until section 'foo'`); `None` if the tree is HQCS-free.
pub fn find_hqcs_construct(node: &ExperimentNode, id_store: &NamedIdStore) -> Option<String> {
    match &node.kind {
        Operation::Send(_) => return Some("send operation".to_owned()),
        Operation::MarkStale(_) => return Some("mark_stale operation".to_owned()),
        Operation::DoUntil(do_until) => {
            let name = id_store.resolve(do_until.uid.0).unwrap_or("<unknown>");
            return Some(format!("do_until section '{name}'"));
        }
        Operation::Match(m) if matches!(m.target, MatchTarget::Variable(_)) => {
            return Some("match on a coprocessor variable".to_owned());
        }
        _ => {}
    }
    node.children
        .iter()
        .find_map(|child| find_hqcs_construct(child, id_store))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::operation::{DoUntil, MarkStale, MarkStaleTarget, Match, Operation, Send};
    use crate::types::{SectionUid, StreamUid, VariableUid};

    fn store() -> NamedIdStore {
        NamedIdStore::default()
    }

    #[test]
    fn declaration_precedence_matches_tripwire_order() {
        let mut hqcs = HqcsDeclarations::default();
        assert_eq!(find_hqcs_declaration(&hqcs), None);
        hqcs.variables.push(VariableDecl {
            ty: VarType::Int32,
            name: None,
            initial: None,
            log_handle: None,
        });
        assert_eq!(find_hqcs_declaration(&hqcs), Some("variables"));
        hqcs.coprocessors.push(CoprocessorDecl {
            label: "gpu".into(),
            payload: vec![],
        });
        assert_eq!(find_hqcs_declaration(&hqcs), Some("coprocessor handles"));
    }

    #[test]
    fn finds_nested_hqcs_construct() {
        let mut id_store = store();
        let uid = SectionUid(id_store.get_or_insert("wait"));
        let mut root = ExperimentNode::new(Operation::Root);
        let mut section = ExperimentNode::new(Operation::DoUntil(DoUntil {
            uid,
            condition: Predicate::IsLive(IsLiveTarget::Variable(VariableUid(0))),
            max_count: 1,
        }));
        section
            .children
            .push(ExperimentNode::new(Operation::MarkStale(MarkStale {
                target: MarkStaleTarget::Variable(VariableUid(0)),
            })));
        root.children.push(section);
        assert_eq!(
            find_hqcs_construct(&root, &id_store),
            Some("do_until section 'wait'".to_owned())
        );
    }

    #[test]
    fn hqcs_free_tree_yields_none() {
        let root = ExperimentNode::new(Operation::Root);
        assert_eq!(find_hqcs_construct(&root, &store()), None);
    }

    #[test]
    fn finds_send_and_match_variable() {
        let mut id_store = store();
        let stream = StreamUid(id_store.get_or_insert("s0"));
        let mut root = ExperimentNode::new(Operation::Root);
        root.children
            .push(ExperimentNode::new(Operation::Send(Send {
                stream,
                args: vec![],
            })));
        assert_eq!(
            find_hqcs_construct(&root, &id_store),
            Some("send operation".to_owned())
        );

        let uid = SectionUid(id_store.get_or_insert("m"));
        let mut root = ExperimentNode::new(Operation::Root);
        root.children
            .push(ExperimentNode::new(Operation::Match(Match {
                uid,
                target: MatchTarget::Variable(VariableUid(0)),
                local: None,
                play_after: vec![],
            })));
        assert_eq!(
            find_hqcs_construct(&root, &id_store),
            Some("match on a coprocessor variable".to_owned())
        );
    }
}
